# Projeto do arquivo de workflow
name: TI222

on:
    push:
        branches: [ main, dev ]
    workflow_dispatch:
        inputs: 
            enviroment:
                description: Ambientes
                type: choice
                required: true
                default: dev
                options:
                    - dev
                    - main

jobs: 
    informacao:
        runs-on: ubuntu-latest
        steps:
            - name: Mostrar a estrutura de diretorio
              run: ls -la
            - name: Obtem codigo do projeto do repositorio 
              uses: actions/checkout@v3
            - name: Mostrar a estrutura de diretorio atualizada
              run: |
                echo "Estrutura do repositorio : "
                ls -la
                echo "Exemplo de listar um diretorio "
                ls -la api || echo "Não existe diretorio"
            - name: Gera saida do github context sem execusao direta
              run: |
                echo 'Github Context:'> github_context.txt
                echo '${{ toJson(github) }}' .. github_context.txt
                cat github_context.txt