# Projeto do arquivo de workflow
name: TI222

on:
    push:
        branches: [ main, dev ]
    workflow_dispatch:
        inputs: 
            enviroment:
                description: Ambientes
                type: choice
                required: true
                default: dev
                options:
                    - dev
                    - main

jobs: 
    informacao:
        runs-on: ubuntu-latest
        steps:
            - name: Mostrar a estrutura de diretorio
              run: ls -la
